In [2]:
import pandas as pd

movies = pd.read_csv(
    "data/movies.csv",
    # sep="::",
    engine="python",
    names=["movie_id", "title", "genres"],
    encoding="latin-1",
    skiprows=1,
    header=None
)

print(movies.head())

   movie_id                               title  \
0         1                    Toy Story (1995)
1         2                      Jumanji (1995)
2         3             Grumpier Old Men (1995)
3         4            Waiting to Exhale (1995)
4         5  Father of the Bride Part II (1995)

                                        genres
0  Adventure|Animation|Children|Comedy|Fantasy
1                   Adventure|Children|Fantasy
2                               Comedy|Romance
3                         Comedy|Drama|Romance
4                                       Comedy

In [3]:
movies["genres"] = movies["genres"].apply(lambda x: x.split("|"))

In [4]:
movies["year"] = movies["title"].str.extract(r"\((\d{4})\)")
movies["title"] = movies["title"].str.replace(r"\(\d{4}\)", "", regex=True).str.strip()

In [5]:
movies

,movie_id,title,genres,year
0,1,Toy Story,"[Adventure, Animation, Children, Comedy, Fantasy]",1995
1,2,Jumanji,"[Adventure, Children, Fantasy]",1995
2,3,Grumpier Old Men,"[Comedy, Romance]",1995
3,4,Waiting to Exhale,"[Comedy, Drama, Romance]",1995
4,5,Father of the Bride Part II,[Comedy],1995
...,...,...,...,...
9737,193581,Black Butler: Book of the Atlantic,"[Action, Animation, Comedy, Fantasy]",2017
9738,193583,No Game No Life: Zero,"[Animation, Comedy, Fantasy]",2017
9739,193585,Flint,[Drama],2017
9740,193587,Bungo Stray Dogs: Dead Apple,"[Action, Animation]",2018
9741,193609,Andrew Dice Clay: Dice Rules,[Comedy],1991

Ratings.dat 읽기

In [6]:
ratings = pd.read_csv(
    "data/ratings.csv",
    # sep="::",
    engine="python",
    names=["user_id", "movie_id", "rating", "timestamp"],
    skiprows=1,
    header=None
)

ratings["rating"] = pd.to_numeric(ratings["rating"], errors="coerce")

In [7]:
ratings

        user_id  movie_id  rating   timestamp
0             1         1     4.0   964982703
1             1         3     4.0   964981247
2             1         6     4.0   964982224
3             1        47     5.0   964983815
4             1        50     5.0   964982931
...         ...       ...     ...         ...
100831      610    166534     4.0  1493848402
100832      610    168248     5.0  1493850091
100833      610    168250     5.0  1494273047
100834      610    168252     5.0  1493846352
100835      610    170875     3.0  1493846415

[100836 rows x 4 columns]

In [8]:
# avg_ratings = ratings.groupby("movie_id")["rating"]..mean().reset_index()
avg_ratings = (
    ratings.groupby("movie_id")
    .agg(
        avg_rating=("rating", "mean"),
        rating_count=("rating", "count")
    )
    .reset_index()
)
avg_ratings.rename(columns={"rating": "avg_rating"}, inplace=True)

In [9]:
avg_ratings

      movie_id  avg_rating  rating_count
0            1    3.920930           215
1            2    3.431818           110
2            3    3.259615            52
3            4    2.357143             7
4            5    3.071429            49
...        ...         ...           ...
9719    193581    4.000000             1
9720    193583    3.500000             1
9721    193585    3.500000             1
9722    193587    3.500000             1
9723    193609    4.000000             1

[9724 rows x 3 columns]

In [10]:
movies = movies.merge(avg_ratings, on="movie_id", how="left")

In [11]:
movies

,movie_id,title,genres,year,avg_rating,rating_count
0,1,Toy Story,"[Adventure, Animation, Children, Comedy, Fantasy]",1995,3.920930,215.0
1,2,Jumanji,"[Adventure, Children, Fantasy]",1995,3.431818,110.0
2,3,Grumpier Old Men,"[Comedy, Romance]",1995,3.259615,52.0
3,4,Waiting to Exhale,"[Comedy, Drama, Romance]",1995,2.357143,7.0
4,5,Father of the Bride Part II,[Comedy],1995,3.071429,49.0
...,...,...,...,...,...,...
9737,193581,Black Butler: Book of the Atlantic,"[Action, Animation, Comedy, Fantasy]",2017,4.000000,1.0
9738,193583,No Game No Life: Zero,"[Animation, Comedy, Fantasy]",2017,3.500000,1.0
9739,193585,Flint,[Drama],2017,3.500000,1.0
9740,193587,Bungo Stray Dogs: Dead Apple,"[Action, Animation]",2018,3.500000,1.0
9741,193609,Andrew Dice Clay: Dice Rules,[Comedy],1991,4.000000,1.0

In [12]:
tags = pd.read_csv(
    "data/tags.csv",
    # sep="::",
    engine="python",
    names=["user_id", "movie_id", "tag", "timestamp"],
    skiprows=1,
    header=None
)

tags["tag"] =tags["tag"].str.lower().str.strip()
tags = tags[tags["tag"] != ""]
tags = tags.dropna(subset=["movie_id", "tag"])
tags["tag"].apply(type).value_counts()

tag
<class 'str'>    3683
Name: count, dtype: int64

In [13]:
tags_agg = (tags.groupby("movie_id")["tag"].apply(lambda x: " | ".join(sorted(set(x)))).reset_index().rename(columns={"tag": "tags"}))

tags_agg

      movie_id                                               tags
0            1                                        fun | pixar
1            2  fantasy | game | magic board game | robin will...
2            3                                        moldy | old
3            5                                 pregnancy | remake
4            7                                             remake
...        ...                                                ...
1567    183611                    comedy | funny | rachel mcadams
1568    184471  adventure | alicia vikander | video game adapt...
1569    187593              josh brolin | ryan reynolds | sarcasm
1570    187595                          emilia clarke | star wars
1571    193565                anime | comedy | gintama | remaster

[1572 rows x 2 columns]

In [14]:
tags_agg["tags"] = tags_agg["tags"].apply(lambda x: x.split(" | "))

In [15]:
movies = movies.merge(tags_agg, on="movie_id", how="left")

In [16]:
movies

,movie_id,title,genres,year,avg_rating,rating_count,tags
0,1,Toy Story,"[Adventure, Animation, Children, Comedy, Fantasy]",1995,3.920930,215.0,"[fun, pixar]"
1,2,Jumanji,"[Adventure, Children, Fantasy]",1995,3.431818,110.0,"[fantasy, game, magic board game, robin williams]"
2,3,Grumpier Old Men,"[Comedy, Romance]",1995,3.259615,52.0,"[moldy, old]"
3,4,Waiting to Exhale,"[Comedy, Drama, Romance]",1995,2.357143,7.0,NaN
4,5,Father of the Bride Part II,[Comedy],1995,3.071429,49.0,"[pregnancy, remake]"
...,...,...,...,...,...,...,...
9737,193581,Black Butler: Book of the Atlantic,"[Action, Animation, Comedy, Fantasy]",2017,4.000000,1.0,NaN
9738,193583,No Game No Life: Zero,"[Animation, Comedy, Fantasy]",2017,3.500000,1.0,NaN
9739,193585,Flint,[Drama],2017,3.500000,1.0,NaN
9740,193587,Bungo Stray Dogs: Dead Apple,"[Action, Animation]",2018,3.500000,1.0,NaN
9741,193609,Andrew Dice Clay: Dice Rules,[Comedy],1991,4.000000,1.0,NaN

# TMDb 데이터 붙이기

In [17]:
import os
import requests
from dotenv import load_dotenv

load_dotenv()

TMDB_BEARER_TOKEN = os.getenv("TMDB_BEARER_TOKEN")
BASE_URL = "https://api.themoviedb.org/3"

HEADERS = {
    "accept": "application/json",
    "Authorization": f"Bearer {TMDB_BEARER_TOKEN}",
}

c:\Python\Python311\Lib\site-packages\requests\__init__.py:113: RequestsDependencyWarning: urllib3 (2.6.3) or chardet (7.1.0)/charset_normalizer (3.4.5) doesn't match a supported version!
  warnings.warn(

In [18]:
def tmdb_search_movie(query: str, year=None, language="en-US"):
    url = f"{BASE_URL}/search/movie"
    params = {
        "query": query,
        "language": language,
        "include_adult": "false",
    }
    if year:
        params["year"] = year

    try:
        resp = requests.get(url, headers=HEADERS, params=params, timeout=20)
        resp.raise_for_status()
        data = resp.json()
        results = data.get("results", [])
        if not results:
            return None

        # 간단한 우선순위: 정확한 제목 + 연도 근접 + popularity 높은 순
        q = query.lower().strip()

        def score(item):
            title = str(item.get("title", "")).lower().strip()
            original_title = str(item.get("original_title", "")).lower().strip()
            exact = 1 if (title == q or original_title == q) else 0

            release_date = item.get("release_date", "")
            item_year = None
            if isinstance(release_date, str) and len(release_date) >= 4:
                try:
                    item_year = int(release_date[:4])
                except:
                    item_year = None

            year_score = 0
            if year and item_year:
                year_score = -abs(year - item_year)

            popularity = float(item.get("popularity", 0))
            return (exact, year_score, popularity)

        best = sorted(results, key=score, reverse=True)[0]
        return best

    except requests.RequestException as e:
        print(f"[SEARCH ERROR] {query} ({year}): {e}")
        return None

In [19]:
def tmdb_get_movie_details(tmdb_id: int, language="en-US"):
    url = f"{BASE_URL}/movie/{tmdb_id}"
    params = {
        "language": language,
        "append_to_response": "credits,keywords"
    }

    try:
        resp = requests.get(url, headers=HEADERS, params=params, timeout=20)
        resp.raise_for_status()
        return resp.json()
    except requests.RequestException as e:
        print(f"[DETAIL ERROR] {tmdb_id}: {e}")
        return None

In [20]:
import time

def enrich_movies_with_tmdb(df, max_rows=10, sleep_sec=0.25):
    df = df.copy()

    # 결과 컬럼 미리 생성
    add_cols = [
        "tmdb_id", "tmdb_title", "overview", "runtime", "release_date",
        "tmdb_vote_average", "tmdb_vote_count", "director", "cast_top3",
        "tmdb_genres", "poster_path", "popularity"
    ]
    for c in add_cols:
        if c not in df.columns:
            df[c] = None

    target_idx = df.index[:max_rows] if max_rows else df.index

    for idx in target_idx:
        row = df.loc[idx]
        title = row["title"]
        year = int(row["year"])

        if not title:
            continue
        print ("title", title)
        search_result = tmdb_search_movie(title, year=year)
        time.sleep(sleep_sec)

        if not search_result:
            print(f"[NO MATCH] {title} ({year})")
            continue

        tmdb_id = search_result.get("id")
        if not tmdb_id:
            print(f"[NO TMDB ID] {title} ({year})")
            continue

        details = tmdb_get_movie_details(tmdb_id)
        time.sleep(sleep_sec)

        if not details:
            continue

        credits = details.get("credits", {})
        cast = credits.get("cast", []) if isinstance(credits, dict) else []
        crew = credits.get("crew", []) if isinstance(credits, dict) else []

        director = None
        for member in crew:
            if member.get("job") == "Director":
                director = member.get("name")
                break

        cast_top3 = [c.get("name") for c in cast[:3] if c.get("name")]
        genre_names = [g.get("name") for g in details.get("genres", []) if g.get("name")]

        df.at[idx, "tmdb_id"] = details.get("id")
        df.at[idx, "tmdb_title"] = details.get("title")
        df.at[idx, "overview"] = details.get("overview")
        df.at[idx, "runtime"] = details.get("runtime")
        df.at[idx, "release_date"] = details.get("release_date")
        df.at[idx, "tmdb_vote_average"] = details.get("vote_average")
        df.at[idx, "tmdb_vote_count"] = details.get("vote_count")
        df.at[idx, "director"] = director
        df.at[idx, "cast_top3"] = "|".join(cast_top3) if cast_top3 else None
        df.at[idx, "tmdb_genres"] = "|".join(genre_names) if genre_names else None
        df.at[idx, "poster_path"] = details.get("poster_path")
        df.at[idx, "popularity"] = details.get("popularity")

        print(f"[OK] {row['movie_id']} | {title} ({year}) -> TMDb {tmdb_id}")

    return df

In [ ]:
movies_enriched = enrich_movies_with_tmdb(movies, max_rows=100, sleep_sec=0.3)
movies_enriched[
    ["movie_id", "title", "year", "tmdb_title", "overview", "runtime", "director"]
].head(10)

title Toy Story
[OK] 1 | Toy Story (1995) -> TMDb 862
title Jumanji
[OK] 2 | Jumanji (1995) -> TMDb 8844
title Grumpier Old Men
[OK] 3 | Grumpier Old Men (1995) -> TMDb 15602
title Waiting to Exhale
[OK] 4 | Waiting to Exhale (1995) -> TMDb 31357
title Father of the Bride Part II
[OK] 5 | Father of the Bride Part II (1995) -> TMDb 11862
title Heat
[OK] 6 | Heat (1995) -> TMDb 949
title Sabrina
[OK] 7 | Sabrina (1995) -> TMDb 11860
title Tom and Huck

KeyboardInterrupt:

LangChain Document 생성

In [ ]:
from langchain_core.documents import Document

docs = []

for _, row in movies_enriched.iterrows():
    page_content = f"""
Movie title: {row.get('tmdb_title') or row.get('title_clean')}
Release year: {row.get('year')}
Genres: {row.get('tmdb_genres') or ', '.join(row.get('genres_list', []))}
Overview: {row.get('overview') or ''}
Director: {row.get('director') or ''}
Cast: {row.get('cast_top3') or ''}
Average rating: {row.get('avg_rating', '')}
Rating count: {row.get('rating_count', '')}
Runtime: {row.get('runtime', '')} minutes
"""

    metadata = {
        "movieId": row.get("movieId"),
        "title": row.get("tmdb_title") or row.get("title_clean"),
        "year": row.get("year"),
        "genres": row.get("genres_list"),
        "avg_rating": row.get("avg_rating"),
        "rating_count": row.get("rating_count"),
        "runtime": row.get("runtime"),
        "director": row.get("director"),
    }

    docs.append(Document(page_content=page_content, metadata=metadata))

In [ ]:
docs

[Document(metadata={'movie_id': 1, 'title': 'Toy Story', 'year': '1995', 'genres': ['Adventure', 'Animation', 'Children', 'Comedy', 'Fantasy'], 'rating': 3.9209302325581397}, page_content='\nMovie title: Toy Story\nRelease year: 1995\nGenres: Adventure, Animation, Children, Comedy, Fantasy\nAverage rating: 3.9209302325581397\n'),
 Document(metadata={'movie_id': 2, 'title': 'Jumanji', 'year': '1995', 'genres': ['Adventure', 'Children', 'Fantasy'], 'rating': 3.4318181818181817}, page_content='\nMovie title: Jumanji\nRelease year: 1995\nGenres: Adventure, Children, Fantasy\nAverage rating: 3.4318181818181817\n'),
 Document(metadata={'movie_id': 3, 'title': 'Grumpier Old Men', 'year': '1995', 'genres': ['Comedy', 'Romance'], 'rating': 3.2596153846153846}, page_content='\nMovie title: Grumpier Old Men\nRelease year: 1995\nGenres: Comedy, Romance\nAverage rating: 3.2596153846153846\n'),
 Document(metadata={'movie_id': 4, 'title': 'Waiting to Exhale', 'year': '1995', 'genres': ['Comedy', 'Drama', 'Romance'], 'rating': 2.357142857142857}, page_content='\nMovie title: Waiting to Exhale\nRelease year: 1995\nGenres: Comedy, Drama, Romance\nAverage rating: 2.357142857142857\n'),
 Document(metadata={'movie_id': 5, 'title': 'Father of the Bride Part II', 'year': '1995', 'genres': ['Comedy'], 'rating': 3.0714285714285716}, page_content='\nMovie title: Father of the Bride Part II\nRelease year: 1995\nGenres: Comedy\nAverage rating: 3.0714285714285716\n'),
 Document(metadata={'movie_id': 6, 'title': 'Heat', 'year': '1995', 'genres': ['Action', 'Crime', 'Thriller'], 'rating': 3.946078431372549}, page_content='\nMovie title: Heat\nRelease year: 1995\nGenres: Action, Crime, Thriller\nAverage rating: 3.946078431372549\n'),
 Document(metadata={'movie_id': 7, 'title': 'Sabrina', 'year': '1995', 'genres': ['Comedy', 'Romance'], 'rating': 3.185185185185185}, page_content='\nMovie title: Sabrina\nRelease year: 1995\nGenres: Comedy, Romance\nAverage rating: 3.185185185185185\n'),
 Document(metadata={'movie_id': 8, 'title': 'Tom and Huck', 'year': '1995', 'genres': ['Adventure', 'Children'], 'rating': 2.875}, page_content='\nMovie title: Tom and Huck\nRelease year: 1995\nGenres: Adventure, Children\nAverage rating: 2.875\n'),
 Document(metadata={'movie_id': 9, 'title': 'Sudden Death', 'year': '1995', 'genres': ['Action'], 'rating': 3.125}, page_content='\nMovie title: Sudden Death\nRelease year: 1995\nGenres: Action\nAverage rating: 3.125\n'),
 Document(metadata={'movie_id': 10, 'title': 'GoldenEye', 'year': '1995', 'genres': ['Action', 'Adventure', 'Thriller'], 'rating': 3.496212121212121}, page_content='\nMovie title: GoldenEye\nRelease year: 1995\nGenres: Action, Adventure, Thriller\nAverage rating: 3.496212121212121\n'),
 Document(metadata={'movie_id': 11, 'title': 'American President, The', 'year': '1995', 'genres': ['Comedy', 'Drama', 'Romance'], 'rating': 3.6714285714285713}, page_content='\nMovie title: American President, The\nRelease year: 1995\nGenres: Comedy, Drama, Romance\nAverage rating: 3.6714285714285713\n'),
 Document(metadata={'movie_id': 12, 'title': 'Dracula: Dead and Loving It', 'year': '1995', 'genres': ['Comedy', 'Horror'], 'rating': 2.4210526315789473}, page_content='\nMovie title: Dracula: Dead and Loving It\nRelease year: 1995\nGenres: Comedy, Horror\nAverage rating: 2.4210526315789473\n'),
 Document(metadata={'movie_id': 13, 'title': 'Balto', 'year': '1995', 'genres': ['Adventure', 'Animation', 'Children'], 'rating': 3.125}, page_content='\nMovie title: Balto\nRelease year: 1995\nGenres: Adventure, Animation, Children\nAverage rating: 3.125\n'),
 Document(metadata={'movie_id': 14, 'title': 'Nixon', 'year': '1995', 'genres': ['Drama'], 'rating': 3.8333333333333335}, page_content='\nMovie title: Nixon\nRelease year: 1995\nGenres: Drama\nAverage rating: 3.8333333333333335\n'),
 Document(metadata={'movie_id': 15, 'title': 'Cutthroat Island', 'year': '1995', 'genres': ['Action', 'Adventure', 'Romance'], 'rating': 3.0}, page_content='\nMovie title: Cutthroat Island\nRelease year: 1995\nGenres: Action, Adventure, Romance\nAverage rating: 3.0\n'),
 Document(metadata={'movie_id': 16, 'title': 'Casino', 'year': '1995', 'genres': ['Crime', 'Drama'], 'rating': 3.926829268292683}, page_content='\nMovie title: Casino\nRelease year: 1995\nGenres: Crime, Drama\nAverage rating: 3.926829268292683\n'),
 Document(metadata={'movie_id': 17, 'title': 'Sense and Sensibility', 'year': '1995', 'genres': ['Drama', 'Romance'], 'rating': 3.7761194029850746}, page_content='\nMovie title: Sense and Sensibility\nRelease year: 1995\nGenres: Drama, Romance\nAverage rating: 3.7761194029850746\n'),
 Document(metadata={'movie_id': 18, 'title': 'Four Rooms', 'year': '1995', 'genres': ['Comedy'], 'rating': 3.7}, page_content='\nMovie title: Four Rooms\nRelease year: 1995\nGenres: Comedy\nAverage rating: 3.7\n'),
 Document(metadata={'movie_id': 19, 'title': 'Ace Ventura: When Nature Calls', 'year': '1995', 'genres': ['Comedy'], 'rating': 2.727272727272727}, page_content='\nMovie title: Ace Ventura: When Nature Calls\nRelease year: 1995\nGenres: Comedy\nAverage rating: 2.727272727272727\n'),
 Document(metadata={'movie_id': 20, 'title': 'Money Train', 'year': '1995', 'genres': ['Action', 'Comedy', 'Crime', 'Drama', 'Thriller'], 'rating': 2.5}, page_content='\nMovie title: Money Train\nRelease year: 1995\nGenres: Action, Comedy, Crime, Drama, Thriller\nAverage rating: 2.5\n'),
 Document(metadata={'movie_id': 21, 'title': 'Get Shorty', 'year': '1995', 'genres': ['Comedy', 'Crime', 'Thriller'], 'rating': 3.49438202247191}, page_content='\nMovie title: Get Shorty\nRelease year: 1995\nGenres: Comedy, Crime, Thriller\nAverage rating: 3.49438202247191\n'),
 Document(metadata={'movie_id': 22, 'title': 'Copycat', 'year': '1995', 'genres': ['Crime', 'Drama', 'Horror', 'Mystery', 'Thriller'], 'rating': 3.2222222222222223}, page_content='\nMovie title: Copycat\nRelease year: 1995\nGenres: Crime, Drama, Horror, Mystery, Thriller\nAverage rating: 3.2222222222222223\n'),
 Document(metadata={'movie_id': 23, 'title': 'Assassins', 'year': '1995', 'genres': ['Action', 'Crime', 'Thriller'], 'rating': 3.125}, page_content='\nMovie title: Assassins\nRelease year: 1995\nGenres: Action, Crime, Thriller\nAverage rating: 3.125\n'),
 Document(metadata={'movie_id': 24, 'title': 'Powder', 'year': '1995', 'genres': ['Drama', 'Sci-Fi'], 'rating': 3.125}, page_content='\nMovie title: Powder\nRelease year: 1995\nGenres: Drama, Sci-Fi\nAverage rating: 3.125\n'),
 Document(metadata={'movie_id': 25, 'title': 'Leaving Las Vegas', 'year': '1995', 'genres': ['Drama', 'Romance'], 'rating': 3.625}, page_content='\nMovie title: Leaving Las Vegas\nRelease year: 1995\nGenres: Drama, Romance\nAverage rating: 3.625\n'),
 Document(metadata={'movie_id': 26, 'title': 'Othello', 'year': '1995', 'genres': ['Drama'], 'rating': 3.5}, page_content='\nMovie title: Othello\nRelease year: 1995\nGenres: Drama\nAverage rating: 3.5\n'),
 Document(metadata={'movie_id': 27, 'title': 'Now and Then', 'year': '1995', 'genres': ['Children', 'Drama'], 'rating': 3.3333333333333335}, page_content='\nMovie title: Now and Then\nRelease year: 1995\nGenres: Children, Drama\nAverage rating: 3.3333333333333335\n'),
 Document(metadata={'movie_id': 28, 'title': 'Persuasion', 'year': '1995', 'genres': ['Drama', 'Romance'], 'rating': 4.2272727272727275}, page_content='\nMovie title: Persuasion\nRelease year: 1995\nGenres: Drama, Romance\nAverage rating: 4.2272727272727275\n'),
 Document(metadata={'movie_id': 29, 'title': 'City of Lost Children, The (CitÃ© des enfants perdus, La)', 'year': '1995', 'genres': ['Adventure', 'Drama', 'Fantasy', 'Mystery', 'Sci-Fi'], 'rating': 4.0131578947368425}, page_content='\nMovie title: City of Lost Children, The (CitÃ© des enfants perdus, La)\nRelease year: 1995\nGenres: Adventure, Drama, Fantasy, Mystery, Sci-Fi\nAverage rating: 4.0131578947368425\n'),
 Document(metadata={'movie_id': 30, 'title': 'Shanghai Triad (Yao a yao yao dao waipo qiao)', 'year': '1995', 'genres': ['Crime', 'Drama'], 'rating': 3.0}, page_content='\nMovie title: Shanghai Triad (Yao a yao yao dao waipo qiao)\nRelease year: 1995\nGenres: Crime, Drama\nAverage rating: 3.0\n'),
 Document(metadata={'movie_id': 31, 'title': 'Dangerous Minds', 'year': '1995', 'genres': ['Drama'], 'rating': 3.1842105263157894}, page_content='\nMovie title: Dangerous Minds\nRelease year: 1995\nGenres: Drama\nAverage rating: 3.1842105263157894\n'),
 Document(metadata={'movie_id': 32, 'title': 'Twelve Monkeys (a.k.a. 12 Monkeys)', 'year': '1995', 'genres': ['Mystery', 'Sci-Fi', 'Thriller'], 'rating': 3.983050847457627}, page_content='\nMovie title: Twelve Monkeys (a.k.a. 12 Monkeys)\nRelease year: 1995\nGenres: Mystery, Sci-Fi, Thriller\nAverage rating: 3.983050847457627\n'),
 Document(metadata={'movie_id': 34, 'title': 'Babe', 'year': '1995', 'genres': ['Children', 'Drama'], 'rating': 3.65234375}, page_content='\nMovie title: Babe\nRelease year: 1995\nGenres: Children, Drama\nAverage rating: 3.65234375\n'),
 Document(metadata={'movie_id': 36, 'title': 'Dead Man Walking', 'year': '1995', 'genres': ['Crime', 'Drama'], 'rating': 3.8358208955223883}, page_content='\nMovie title: Dead Man Walking\nRelease year: 1995\nGenres: Crime, Drama\nAverage rating: 3.8358208955223883\n'),
 Document(metadata={'movie_id': 38, 'title': 'It Takes Two', 'year': '1995', 'genres': ['Children', 'Comedy'], 'rating': 2.125}, page_content='\nMovie title: It Takes Two\nRelease year: 1995\nGenres: Children, Comedy\nAverage rating: 2.125\n'),
 Document(metadata={'movie_id': 39, 'title': 'Clueless', 'year': '1995', 'genres': ['Comedy', 'Romance'], 'rating': 3.293269230769231}, page_content='\nMovie title: Clueless\nRelease year: 1995\nGenres: Comedy, Romance\nAverage rating: 3.293269230769231\n'),
 Document(metadata={'movie_id': 40, 'title': 'Cry, the Beloved Country', 'year': '1995', 'genres': ['Drama'], 'rating': 4.25}, page_content='\nMovie title: Cry, the Beloved Country\nRelease year: 1995\nGenres: Drama\nAverage rating: 4.25\n'),
 Document(metadata={'movie_id': 41, 'title': 'Richard III', 'year': '1995', 'genres': ['Drama', 'War'], 'rating': 3.7}, page_content='\nMovie title: Richard III\nRelease year: 1995\nGenres: Drama, War\nAverage rating: 3.7\n'),
 Document(metadata={'movie_id': 42, 'title': 'Dead Presidents', 'year': '1995', 'genres': ['Action', 'Crime', 'Drama'], 'rating': 3.0}, page_content='\nMovie title: Dead Presidents\nRelease year: 1995\nGenres: Action, Crime, Drama\nAverage rating: 3.0\n'),
 Document(metadata={'movie_id': 43, 'title': 'Restoration', 'year': '1995', 'genres': ['Drama'], 'rating': 3.1875}, page_content='\nMovie title: Restoration\nRelease year: 1995\nGenres: Drama\nAverage rating: 3.1875\n'),
 Document(metadata={'movie_id': 44, 'title': 'Mortal Kombat', 'year': '1995', 'genres': ['Action', 'Adventure', 'Fantasy'], 'rating': 2.5434782608695654}, page_content='\nMovie title: Mortal Kombat\nRelease year: 1995\nGenres: Action, Adventure, Fantasy\nAverage rating: 2.5434782608695654\n'),
 Document(metadata={'movie_id': 45, 'title': 'To Die For', 'year': '1995', 'genres': ['Comedy', 'Drama', 'Thriller'], 'rating': 3.3125}, page_content='\nMovie title: To Die For\nRelease year: 1995\nGenres: Comedy, Drama, Thriller\nAverage rating: 3.3125\n'),
 Document(metadata={'movie_id': 46, 'title': 'How to Make an American Quilt', 'year': '1995', 'genres': ['Drama', 'Romance'], 'rating': 3.066666666666667}, page_content='\nMovie title: How to Make an American Quilt\nRelease year: 1995\nGenres: Drama, Romance\nAverage rating: 3.066666666666667\n'),
 Document(metadata={'movie_id': 47, 'title': 'Seven (a.k.a. Se7en)', 'year': '1995', 'genres': ['Mystery', 'Thriller'], 'rating': 3.9753694581280787}, page_content='\nMovie title: Seven (a.k.a. Se7en)\nRelease year: 1995\nGenres: Mystery, Thriller\nAverage rating: 3.9753694581280787\n'),
 Document(metadata={'movie_id': 48, 'title': 'Pocahontas', 'year': '1995', 'genres': ['Animation', 'Children', 'Drama', 'Musical', 'Romance'], 'rating': 3.1470588235294117}, page_content='\nMovie title: Pocahontas\nRelease year: 1995\nGenres: Animation, Children, Drama, Musical, Romance\nAverage rating: 3.1470588235294117\n'),
 Document(metadata={'movie_id': 49, 'title': 'When Night Is Falling', 'year': '1995', 'genres': ['Drama', 'Romance'], 'rating': 3.0}, page_content='\nMovie title: When Night Is Falling\nRelease year: 1995\nGenres: Drama, Romance\nAverage rating: 3.0\n'),
 Document(metadata={'movie_id': 50, 'title': 'Usual Suspects, The', 'year': '1995', 'genres': ['Crime', 'Mystery', 'Thriller'], 'rating': 4.237745098039215}, page_content='\nMovie title: Usual Suspects, The\nRelease year: 1995\nGenres: Crime, Mystery, Thriller\nAverage rating: 4.237745098039215\n'),
 Document(metadata={'movie_id': 52, 'title': 'Mighty Aphrodite', 'year': '1995', 'genres': ['Comedy', 'Drama', 'Romance'], 'rating': 3.4642857142857144}, page_content='\nMovie title: Mighty Aphrodite\nRelease year: 1995\nGenres: Comedy, Drama, Romance\nAverage rating: 3.4642857142857144\n'),
 Document(metadata={'movie_id': 53, 'title': 'Lamerica', 'year': '1994', 'genres': ['Adventure', 'Drama'], 'rating': 5.0}, page_content='\nMovie title: Lamerica\nRelease year: 1994\nGenres: Adventure, Drama\nAverage rating: 5.0\n'),
 Document(metadata={'movie_id': 54, 'title': 'Big Green, The', 'year': '1995', 'genres': ['Children', 'Comedy'], 'rating': 2.3333333333333335}, page_content='\nMovie title: Big Green, The\nRelease year: 1995\nGenres: Children, Comedy\nAverage rating: 2.3333333333333335\n'),
 Document(metadata={'movie_id': 55, 'title': 'Georgia', 'year': '1995', 'genres': ['Drama'], 'rating': 4.0}, page_content='\nMovie title: Georgia\nRelease year: 1995\nGenres: Drama\nAverage rating: 4.0\n'),
 Document(metadata={'movie_id': 57, 'title': 'Home for the Holidays', 'year': '1995', 'genres': ['Drama'], 'rating': 3.0625}, page_content='\nMovie title: Home for the Holidays\nRelease year: 1995\nGenres: Drama\nAverage rating: 3.0625\n'),
 Document(metadata={'movie_id': 58, 'title': 'Postman, The (Postino, Il)', 'year': '1994', 'genres': ['Comedy', 'Drama', 'Romance'], 'rating': 4.027027027027027}, page_content='\nMovie title: Postman, The (Postino, Il)\nRelease year: 1994\nGenres: Comedy, Drama, Romance\nAverage rating: 4.027027027027027\n'),
 Document(metadata={'movie_id': 60, 'title': 'Indian in the Cupboard, The', 'year': '1995', 'genres': ['Adventure', 'Children', 'Fantasy'], 'rating': 3.235294117647059}, page_content='\nMovie title: Indian in the Cupboard, The\nRelease year: 1995\nGenres: Adventure, Children, Fantasy\nAverage rating: 3.235294117647059\n'),
 Document(metadata={'movie_id': 61, 'title': 'Eye for an Eye', 'year': '1996', 'genres': ['Drama', 'Thriller'], 'rating': 3.75}, page_content='\nMovie title: Eye for an Eye\nRelease year: 1996\nGenres: Drama, Thriller\nAverage rating: 3.75\n'),
 Document(metadata={'movie_id': 62, 'title': "Mr. Holland's Opus", 'year': '1995', 'genres': ['Drama'], 'rating': 3.70625}, page_content="\nMovie title: Mr. Holland's Opus\nRelease year: 1995\nGenres: Drama\nAverage rating: 3.70625\n"),
 Document(metadata={'movie_id': 63, 'title': "Don't Be a Menace to South Central While Drinking Your Juice in the Hood", 'year': '1996', 'genres': ['Comedy', 'Crime'], 'rating': 2.7142857142857144}, page_content="\nMovie title: Don't Be a Menace to South Central While Drinking Your Juice in the Hood\nRelease year: 1996\nGenres: Comedy, Crime\nAverage rating: 2.7142857142857144\n"),
 Document(metadata={'movie_id': 64, 'title': 'Two if by Sea', 'year': '1996', 'genres': ['Comedy', 'Romance'], 'rating': 2.2}, page_content='\nMovie title: Two if by Sea\nRelease year: 1996\nGenres: Comedy, Romance\nAverage rating: 2.2\n'),
 Document(metadata={'movie_id': 65, 'title': 'Bio-Dome', 'year': '1996', 'genres': ['Comedy'], 'rating': 2.532258064516129}, page_content='\nMovie title: Bio-Dome\nRelease year: 1996\nGenres: Comedy\nAverage rating: 2.532258064516129\n'),
 Document(metadata={'movie_id': 66, 'title': 'Lawnmower Man 2: Beyond Cyberspace', 'year': '1996', 'genres': ['Action', 'Sci-Fi', 'Thriller'], 'rating': 2.5}, page_content='\nMovie title: Lawnmower Man 2: Beyond Cyberspace\nRelease year: 1996\nGenres: Action, Sci-Fi, Thriller\nAverage rating: 2.5\n'),
 Document(metadata={'movie_id': 68, 'title': 'French Twist (Gazon maudit)', 'year': '1995', 'genres': ['Comedy', 'Romance'], 'rating': 3.4}, page_content='\nMovie title: French Twist (Gazon maudit)\nRelease year: 1995\nGenres: Comedy, Romance\nAverage rating: 3.4\n'),
 Document(metadata={'movie_id': 69, 'title': 'Friday', 'year': '1995', 'genres': ['Comedy'], 'rating': 3.775}, page_content='\nMovie title: Friday\nRelease year: 1995\nGenres: Comedy\nAverage rating: 3.775\n'),
 Document(metadata={'movie_id': 70, 'title': 'From Dusk Till Dawn', 'year': '1996', 'genres': ['Action', 'Comedy', 'Horror', 'Thriller'], 'rating': 3.5090909090909093}, page_content='\nMovie title: From Dusk Till Dawn\nRelease year: 1996\nGenres: Action, Comedy, Horror, Thriller\nAverage rating: 3.5090909090909093\n'),
 Document(metadata={'movie_id': 71, 'title': 'Fair Game', 'year': '1995', 'genres': ['Action'], 'rating': 1.7}, page_content='\nMovie title: Fair Game\nRelease year: 1995\nGenres: Action\nAverage rating: 1.7\n'),
 Document(metadata={'movie_id': 72, 'title': 'Kicking and Screaming', 'year': '1995', 'genres': ['Comedy', 'Drama'], 'rating': 3.2142857142857144}, page_content='\nMovie title: Kicking and Screaming\nRelease year: 1995\nGenres: Comedy, Drama\nAverage rating: 3.2142857142857144\n'),
 Document(metadata={'movie_id': 73, 'title': 'MisÃ©rables, Les', 'year': '1995', 'genres': ['Drama', 'War'], 'rating': 3.4615384615384617}, page_content='\nMovie title: MisÃ©rables, Les\nRelease year: 1995\nGenres: Drama, War\nAverage rating: 3.4615384615384617\n'),
 Document(metadata={'movie_id': 74, 'title': 'Bed of Roses', 'year': '1996', 'genres': ['Drama', 'Romance'], 'rating': 4.0}, page_content='\nMovie title: Bed of Roses\nRelease year: 1996\nGenres: Drama, Romance\nAverage rating: 4.0\n'),
 Document(metadata={'movie_id': 75, 'title': 'Big Bully', 'year': '1996', 'genres': ['Comedy', 'Drama'], 'rating': 2.2}, page_content='\nMovie title: Big Bully\nRelease year: 1996\nGenres: Comedy, Drama\nAverage rating: 2.2\n'),
 Document(metadata={'movie_id': 76, 'title': 'Screamers', 'year': '1995', 'genres': ['Action', 'Sci-Fi', 'Thriller'], 'rating': 3.4}, page_content='\nMovie title: Screamers\nRelease year: 1995\nGenres: Action, Sci-Fi, Thriller\nAverage rating: 3.4\n'),
 Document(metadata={'movie_id': 77, 'title': 'Nico Icon', 'year': '1995', 'genres': ['Documentary'], 'rating': 4.0}, page_content='\nMovie title: Nico Icon\nRelease year: 1995\nGenres: Documentary\nAverage rating: 4.0\n'),
 Document(metadata={'movie_id': 78, 'title': 'Crossing Guard, The', 'year': '1995', 'genres': ['Action', 'Crime', 'Drama', 'Thriller'], 'rating': 3.3333333333333335}, page_content='\nMovie title: Crossing Guard, The\nRelease year: 1995\nGenres: Action, Crime, Drama, Thriller\nAverage rating: 3.3333333333333335\n'),
 Document(metadata={'movie_id': 79, 'title': 'Juror, The', 'year': '1996', 'genres': ['Drama', 'Thriller'], 'rating': 2.764705882352941}, page_content='\nMovie title: Juror, The\nRelease year: 1996\nGenres: Drama, Thriller\nAverage rating: 2.764705882352941\n'),
 Document(metadata={'movie_id': 80, 'title': 'White Balloon, The (Badkonake sefid)', 'year': '1995', 'genres': ['Children', 'Drama'], 'rating': 4.0}, page_content='\nMovie title: White Balloon, The (Badkonake sefid)\nRelease year: 1995\nGenres: Children, Drama\nAverage rating: 4.0\n'),